#!/bin/bash

if ! command -v xclip &> /dev/null
then
    echo "xclip could not be found. Please install xclip."
    exit 1
fi

if [ "$#" -ne 2 ]; then
    echo "Usage: collect from,to file"
    exit 1
fi

range=$1
file=$2

sed -n "${range}p" "$file" | xclip -selection clipboard

echo "Lines $1 from file '$file' have been copied to the clipboard."

