#!/bin/bash

map() {
  local x=$1
  local in_min=$2
  local in_max=$3
  local out_min=$4
  local out_max=$5

  echo "scale=2; ($x - $in_min) * ($out_max - $out_min) / ($in_max - $in_min) + $out_min" | bc
}

if [ $# -ne 1 ]; then
  echo "Usage: $0 x:in_min:in_max:out_min:out_max"
  exit 1
fi

IFS=':' read -r -a values <<< "$1"

if [ ${#values[@]} -ne 5 ]; then
  echo "Invalid input. Please provide exactly 5 values separated by ':'."
  exit 1
fi

result=$(map "${values[0]}" "${values[1]}" "${values[2]}" "${values[3]}" "${values[4]}")

echo "Result: $result"

