#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <filename_with_extension>"
    exit 1
fi

filename_with_extension="$1"
filename_without_extension=$(basename -- "$filename_with_extension")
filename_without_extension="${filename_without_extension%.*}"

echo -n "$filename_without_extension" | xclip -selection clipboard

echo "Filename without extension '$filename_without_extension' copied to clipboard."

